  Process Memory Usage: 74.94 MB
  Total Memory: 15788.21 MB
  Used Memory: 3178.56 MB (22.60%)
  Available Memory: 12217.46 MB

  Process Memory Usage: 75.44 MB
  Total Memory: 15788.21 MB
  Used Memory: 3343.14 MB (23.70%)
  Available Memory: 12052.91 MB

Traceback (most recent call last):
  File "/home/ubuntu/ray-data-eval/ray_data_eval/microbenchmarks/raydata/producer_consumer_gpu.py", line 79, in <module>
    bench(args.mem_limit)
  File "/home/ubuntu/ray-data-eval/ray_data_eval/microbenchmarks/raydata/producer_consumer_gpu.py", line 46, in bench
    ray.init(num_cpus=NUM_CPUS, num_gpus=NUM_GPUS, object_store_memory= min(12, mem_limit) * GB, include_dashboard=False)
  File "/home/ubuntu/ray/python/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ray/python/ray/_private/worker.py", line 1714, in init
    _global_node = ray._private.node.Node(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ray/python/ray/_private/node.py", line 339, in __init__
    self.start_ray_processes()
  File "/home/ubuntu/ray/python/ray/_private/node.py", line 1411, in start_ray_processes
    resource_spec = self.get_resource_spec()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ray/python/ray/_private/node.py", line 583, in get_resource_spec
    ).resolve(is_head=self.head, node_ip_address=self.node_ip_address)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ray/python/ray/_private/resource_spec.py", line 297, in resolve
    raise ValueError(
ValueError: After taking into account object store and redis memory usage, the amount of memory on this node available for tasks and actors (-1.17 GB) is less than -7% of total. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
  Process Memory Usage: 75.44 MB
  Total Memory: 15788.21 MB
  Used Memory: 3380.82 MB (23.90%)
  Available Memory: 12015.23 MB

  Process Memory Usage: 75.44 MB
  Total Memory: 15788.21 MB
  Used Memory: 3396.03 MB (24.00%)
  Available Memory: 12000.02 MB

  Process Memory Usage: 75.44 MB
  Total Memory: 15788.21 MB
  Used Memory: 3396.52 MB (24.00%)
  Available Memory: 11999.53 MB

Memory tracking interrupted, shutting down.Exception ignored in atexit callback
: <function _exit_function at 0x73b5335b3880>
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/multiprocessing/util.py", line 360, in _exit_function
    p.join()
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt: 
